pipeline {
    agent any

    environment {
        SOLUTION_FILE = "SSIS Intro.sln"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'feature/build-pipeline', url: 'https://github.com/jawadtimzit/SSIS-Intro.git'
            }
        }

        stage('Build SSIS Project') {
            steps {
                script {
                    // Get MSBuild tool path from Jenkins Global Tool Configuration
                    def msbuild = tool name: 'MSBUILD_2022', type: 'hudson.plugins.msbuild.MsBuildInstallation'
                    
                    bat "\"${msbuild}\" \"${env.SOLUTION_FILE}\" /t:Rebuild /p:Configuration=Development /nologo /verbosity:minimal"
                }
            }
        }

        stage('Archive Artifacts') {
            steps {
                archiveArtifacts artifacts: '**/*.dtsx', fingerprint: true
            }
        }
    }

    post {
        success {
            echo "SSIS project built successfully with MSBUILD_2022"
        }
        failure {
            echo "Build failed. Check logs for errors.."
        }
    }
}